source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

target 'SwiftPushRepairingManagement' do

pod 'DZNEmptyDataSet' #默认页面（没有数据）

pod 'Kingfisher'

pod 'Onboard'   #启动页

#pod 'Alamofire'  #  网络请求

#pod 'AlamofireImage', '~> 3.5'

pod 'SwiftyJSON'

pod 'SnapKit', '~> 4.0.0'
#pod 'JXPhotoBrowser'

pod 'ObjectMapper'

pod 'Moya/RxSwift'

pod 'HandyJSON', '4.2.0'

pod 'YYKit'

pod 'MJExtension'

pod 'MJRefresh'


end 
